<?php

return [
    'engagement' => [
        'score_weights' => [
            'email_open' => 1,
            'email_click' => 3,
            'content_view' => 2,
            'approval' => 5,
        ],
        'tiers' => [
            1 => [
                'name' => 'Premium',
                'min_score' => 80,
                'description' => 'Highly engaged, priority treatment',
                'email_frequency' => 'daily',
                'content_personalization' => true,
                'rvm_enabled' => true,
            ],
            2 => [
                'name' => 'Active',
                'min_score' => 60,
                'description' => 'Regular engagement, personalized content',
                'email_frequency' => 'every_other_day',
                'content_personalization' => true,
                'rvm_enabled' => false,
            ],
            3 => [
                'name' => 'Moderate',
                'min_score' => 40,
                'description' => 'Some engagement, standard communication',
                'email_frequency' => 'weekly',
                'content_personalization' => false,
                'rvm_enabled' => false,
            ],
            4 => [
                'name' => 'Passive',
                'min_score' => 0,
                'description' => 'Low engagement, basic communication',
                'email_frequency' => 'bi_weekly',
                'content_personalization' => false,
                'rvm_enabled' => false,
            ],
        ],
    ],
    'email' => [
        'from_name' => 'Sarah',
        'from_email' => env('MAIL_FROM_ADDRESS', 'sarah@fibonacco.com'),
        'reply_to' => env('MAIL_REPLY_TO', 'reply@fibonacco.com'),
    ],
    'services' => [
        'appointment_booking' => [
            'name' => 'Online Appointment Booking',
            'description' => 'Let customers book appointments 24/7',
            'short_description' => 'Never miss a booking',
            'benefit' => 'Increase appointments by 30%',
            'auto_provision' => true,
            'meeting_topic' => 'Optimize your booking flow',
        ],
        'review_automation' => [
            'name' => 'Automated Review Requests',
            'description' => 'Automatically ask for reviews after service',
            'short_description' => 'Get 3x more reviews',
            'benefit' => 'Boost your online reputation',
            'auto_provision' => true,
            'meeting_topic' => 'Launch your review campaign',
        ],
        'invoice_automation' => [
            'name' => 'Invoice Automation',
            'description' => 'Automate invoices, reminders, and payment tracking',
            'short_description' => 'Get paid on time',
            'benefit' => 'Reduce overdue invoices',
            'auto_provision' => true,
            'meeting_topic' => 'Streamline your billing workflow',
        ],
        'social_automation' => [
            'name' => 'Social Automation',
            'description' => 'Automate social content posting across channels',
            'short_description' => 'Stay active on social',
            'benefit' => 'Increase visibility',
            'auto_provision' => false,
            'meeting_topic' => 'Plan your content calendar',
        ],
        'email_campaigns' => [
            'name' => 'Email Campaigns',
            'description' => 'Engage customers with targeted email campaigns',
            'short_description' => 'Drive repeat business',
            'benefit' => 'Grow retention',
            'auto_provision' => false,
            'meeting_topic' => 'Design your first campaign',
        ],
        'loyalty_program' => [
            'name' => 'Loyalty Program',
            'description' => 'Reward customers and encourage repeat visits',
            'short_description' => 'Build loyalty',
            'benefit' => 'Boost repeat visits',
            'auto_provision' => false,
            'meeting_topic' => 'Launch your loyalty program',
        ],
        'sms_marketing' => [
            'name' => 'SMS Marketing',
            'description' => 'Send timely promotions via SMS',
            'short_description' => 'Reach customers fast',
            'benefit' => 'Increase conversions',
            'auto_provision' => false,
            'meeting_topic' => 'Craft your first SMS campaign',
        ],
        'sms_reminders' => [
            'name' => 'SMS Reminders',
            'description' => 'Remind customers of upcoming appointments',
            'short_description' => 'Reduce no-shows',
            'benefit' => 'Improve attendance',
            'auto_provision' => false,
        ],
        'calendar_sync' => [
            'name' => 'Calendar Sync',
            'description' => 'Sync booking data with your calendar tools',
            'short_description' => 'Stay organized',
            'benefit' => 'Reduce conflicts',
            'auto_provision' => false,
        ],
        'buffer_time' => [
            'name' => 'Buffer Time',
            'description' => 'Automatically add padding between appointments',
            'short_description' => 'Avoid back-to-back bookings',
            'benefit' => 'Create breathing room',
            'auto_provision' => false,
        ],
        'review_widget' => [
            'name' => 'Review Widget',
            'description' => 'Embed review highlights on your site',
            'short_description' => 'Showcase trust',
            'benefit' => 'Boost conversions',
            'auto_provision' => false,
        ],
        'response_templates' => [
            'name' => 'Response Templates',
            'description' => 'Speed up review responses with templates',
            'short_description' => 'Respond faster',
            'benefit' => 'Improve engagement',
            'auto_provision' => false,
        ],
        'reputation_alerts' => [
            'name' => 'Reputation Alerts',
            'description' => 'Get alerts for new reviews',
            'short_description' => 'Stay informed',
            'benefit' => 'Protect reputation',
            'auto_provision' => false,
        ],
        'payment_reminders' => [
            'name' => 'Payment Reminders',
            'description' => 'Automated payment reminder messages',
            'short_description' => 'Reduce late payments',
            'benefit' => 'Improve cash flow',
            'auto_provision' => false,
        ],
        'late_fees' => [
            'name' => 'Late Fees',
            'description' => 'Apply late fees automatically',
            'short_description' => 'Encourage timely payment',
            'benefit' => 'Reduce delinquencies',
            'auto_provision' => false,
        ],
        'payment_plans' => [
            'name' => 'Payment Plans',
            'description' => 'Offer structured payment plans',
            'short_description' => 'Flexible options',
            'benefit' => 'Close more deals',
            'auto_provision' => false,
        ],
        'content_templates' => [
            'name' => 'Content Templates',
            'description' => 'Reusable templates for social posts',
            'short_description' => 'Post faster',
            'benefit' => 'Consistent brand voice',
            'auto_provision' => false,
        ],
        'hashtag_research' => [
            'name' => 'Hashtag Research',
            'description' => 'Find high-performing hashtags',
            'short_description' => 'Improve reach',
            'benefit' => 'Grow visibility',
            'auto_provision' => false,
        ],
        'post_scheduling' => [
            'name' => 'Post Scheduling',
            'description' => 'Schedule posts in advance',
            'short_description' => 'Stay consistent',
            'benefit' => 'Save time',
            'auto_provision' => false,
        ],
        'subject_line_testing' => [
            'name' => 'Subject Line Testing',
            'description' => 'A/B test subject lines for better open rates',
            'short_description' => 'Improve opens',
            'benefit' => 'Increase engagement',
            'auto_provision' => false,
        ],
        'segmentation' => [
            'name' => 'Segmentation',
            'description' => 'Target the right customers',
            'short_description' => 'Personalize outreach',
            'benefit' => 'Higher conversions',
            'auto_provision' => false,
        ],
        'automated_drip' => [
            'name' => 'Automated Drip',
            'description' => 'Automated nurture sequences',
            'short_description' => 'Stay top of mind',
            'benefit' => 'Increase lifetime value',
            'auto_provision' => false,
        ],
    ],
    'upsell_map' => [
        'appointment_booking' => ['sms_reminders', 'calendar_sync', 'buffer_time'],
        'review_automation' => ['review_widget', 'response_templates', 'reputation_alerts'],
        'invoice_automation' => ['payment_reminders', 'late_fees', 'payment_plans'],
        'social_automation' => ['content_templates', 'hashtag_research', 'post_scheduling'],
        'email_campaigns' => ['subject_line_testing', 'segmentation', 'automated_drip'],
    ],
];
