#!/bin/bash
# Railway Environment Variables Setup Commands
# Generated: Thu Feb  5 11:37:58 EST 2026
# Run this script to set all variables

set -e

echo "🚀 Setting Railway Environment Variables..."
echo ""

# CC API Service
echo "Setting CC API variables..."
railway variables --set "APP_NAME=LearningCenter" --service "CC API"
railway variables --set "APP_ENV=production" --service "CC API"
railway variables --set "APP_DEBUG=false" --service "CC API"
railway variables --set "APP_URL=" --service "CC API"
railway variables --set "DB_CONNECTION=pgsql" --service "CC API"
railway variables --set "DB_HOST=" --service "CC API"
railway variables --set "DB_PORT=5432" --service "CC API"
railway variables --set "DB_DATABASE=" --service "CC API"
railway variables --set "DB_USERNAME=" --service "CC API"
railway variables --set "DB_PASSWORD=" --service "CC API"
railway variables --set "REDIS_HOST=" --service "CC API"
railway variables --set "REDIS_PORT=6379" --service "CC API"
railway variables --set "QUEUE_CONNECTION=redis" --service "CC API"
railway variables --set "REDIS_QUEUE_CONNECTION=default" --service "CC API"
railway variables --set "REDIS_QUEUE=default" --service "CC API"
railway variables --set "SESSION_DRIVER=redis" --service "CC API"
railway variables --set "CACHE_DRIVER=redis" --service "CC API"
railway variables --set "LOG_CHANNEL=stack" --service "CC API"
railway variables --set "LOG_LEVEL=info" --service "CC API"
railway variables --set "HORIZON_PREFIX=horizon" --service "CC API"
railway variables --set "OPENROUTER_API_KEY=" --service "CC API"
railway variables --set "ELEVEN_LABS_API_KEY=" --service "CC API"
railway variables --set "AI_GATEWAY_URL=https://ai-gateway.fibonacco.com" --service "CC API"
railway variables --set "AI_TOOLS_PLATFORM=fibonacco" --service "CC API"
railway variables --set "AI_TOOLS_PROVIDER=openrouter" --service "CC API"
railway variables --set "AI_TOOLS_LOGGING=true" --service "CC API"
railway variables --set "AI_TOOLS_LOG_CHANNEL=stack" --service "CC API"

# Queue Worker Service
echo "Setting Queue Worker variables..."
railway variables --set "APP_NAME=LearningCenter" --service "CRM-CC-LC Queues"
railway variables --set "APP_ENV=production" --service "CRM-CC-LC Queues"
railway variables --set "APP_DEBUG=false" --service "CRM-CC-LC Queues"
railway variables --set "DB_CONNECTION=pgsql" --service "CRM-CC-LC Queues"
railway variables --set "DB_HOST=" --service "CRM-CC-LC Queues"
railway variables --set "DB_PORT=5432" --service "CRM-CC-LC Queues"
railway variables --set "DB_DATABASE=" --service "CRM-CC-LC Queues"
railway variables --set "DB_USERNAME=" --service "CRM-CC-LC Queues"
railway variables --set "DB_PASSWORD=" --service "CRM-CC-LC Queues"
railway variables --set "REDIS_HOST=" --service "CRM-CC-LC Queues"
railway variables --set "REDIS_PORT=6379" --service "CRM-CC-LC Queues"
railway variables --set "QUEUE_CONNECTION=redis" --service "CRM-CC-LC Queues"
railway variables --set "REDIS_QUEUE_CONNECTION=default" --service "CRM-CC-LC Queues"
railway variables --set "REDIS_QUEUE=default" --service "CRM-CC-LC Queues"
railway variables --set "SESSION_DRIVER=redis" --service "CRM-CC-LC Queues"
railway variables --set "CACHE_DRIVER=redis" --service "CRM-CC-LC Queues"
railway variables --set "LOG_CHANNEL=stack" --service "CRM-CC-LC Queues"
railway variables --set "LOG_LEVEL=info" --service "CRM-CC-LC Queues"

# Scheduler Service
echo "Setting Scheduler variables..."
railway variables --set "APP_NAME=LearningCenter" --service "CC-CRM-LC Scheduler"
railway variables --set "APP_ENV=production" --service "CC-CRM-LC Scheduler"
railway variables --set "APP_DEBUG=false" --service "CC-CRM-LC Scheduler"
railway variables --set "DB_CONNECTION=pgsql" --service "CC-CRM-LC Scheduler"
railway variables --set "DB_HOST=" --service "CC-CRM-LC Scheduler"
railway variables --set "DB_PORT=5432" --service "CC-CRM-LC Scheduler"
railway variables --set "DB_DATABASE=" --service "CC-CRM-LC Scheduler"
railway variables --set "DB_USERNAME=" --service "CC-CRM-LC Scheduler"
railway variables --set "DB_PASSWORD=" --service "CC-CRM-LC Scheduler"
railway variables --set "REDIS_HOST=" --service "CC-CRM-LC Scheduler"
railway variables --set "REDIS_PORT=6379" --service "CC-CRM-LC Scheduler"
railway variables --set "QUEUE_CONNECTION=redis" --service "CC-CRM-LC Scheduler"
railway variables --set "REDIS_QUEUE_CONNECTION=default" --service "CC-CRM-LC Scheduler"
railway variables --set "REDIS_QUEUE=default" --service "CC-CRM-LC Scheduler"
railway variables --set "SESSION_DRIVER=redis" --service "CC-CRM-LC Scheduler"
railway variables --set "CACHE_DRIVER=redis" --service "CC-CRM-LC Scheduler"
railway variables --set "LOG_CHANNEL=stack" --service "CC-CRM-LC Scheduler"
railway variables --set "LOG_LEVEL=info" --service "CC-CRM-LC Scheduler"

# Frontend Service
echo "Setting Frontend variables..."
railway variables --set "VITE_API_ENDPOINT=/api" --service "CC-CRM-LC-FOA Front"
railway variables --set "VITE_API_URL=/api" --service "CC-CRM-LC-FOA Front"
railway variables --set "NODE_ENV=production" --service "CC-CRM-LC-FOA Front"

echo ""
echo "✅ All variables set!"
echo ""
echo "⚠️  Don't forget to generate APP_KEY:"
echo "   railway run --service 'CC API' 'php artisan key:generate --show'"
echo "   Then set it: railway variables --set 'APP_KEY=<key>' --service 'CC API'"
