<?php

namespace Database\Seeders\Operations;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MetricDefinitionsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        if (DB::getDriverName() !== 'pgsql') {
            $this->command->warn('Metric definitions seeder requires PostgreSQL. Skipping...');
            return;
        }

        $metrics = [
            // Financial Metrics
            [
                'id' => DB::raw('gen_random_uuid()'),
                'metric_key' => 'financial.mrr',
                'name' => 'Monthly Recurring Revenue',
                'description' => 'Total monthly recurring revenue from all customers',
                'category' => 'financial',
                'subcategory' => 'revenue',
                'data_type' => 'currency',
                'unit' => 'USD',
                'decimal_places' => 2,
                'aggregation_method' => 'sum',
                'rollup_intervals' => json_encode(['hourly', 'daily', 'weekly', 'monthly']),
                'collection_method' => 'computed',
                'ai_importance' => 'critical',
                'is_active' => true,
            ],
            [
                'id' => DB::raw('gen_random_uuid()'),
                'metric_key' => 'financial.arr',
                'name' => 'Annual Recurring Revenue',
                'description' => 'Annual recurring revenue (MRR * 12)',
                'category' => 'financial',
                'subcategory' => 'revenue',
                'data_type' => 'currency',
                'unit' => 'USD',
                'decimal_places' => 2,
                'aggregation_method' => 'computed',
                'rollup_intervals' => json_encode(['monthly', 'quarterly', 'yearly']),
                'collection_method' => 'computed',
                'ai_importance' => 'critical',
                'is_active' => true,
            ],
            [
                'id' => DB::raw('gen_random_uuid()'),
                'metric_key' => 'financial.churn_rate',
                'name' => 'Churn Rate',
                'description' => 'Percentage of customers who churned',
                'category' => 'financial',
                'subcategory' => 'retention',
                'data_type' => 'percentage',
                'unit' => '%',
                'decimal_places' => 2,
                'aggregation_method' => 'avg',
                'rollup_intervals' => json_encode(['daily', 'weekly', 'monthly']),
                'warning_threshold' => 5.0,
                'warning_direction' => 'above',
                'critical_threshold' => 10.0,
                'critical_direction' => 'above',
                'collection_method' => 'computed',
                'ai_importance' => 'high',
                'is_active' => true,
            ],
            [
                'id' => DB::raw('gen_random_uuid()'),
                'metric_key' => 'financial.arpu',
                'name' => 'Average Revenue Per User',
                'description' => 'Average monthly revenue per paying customer',
                'category' => 'financial',
                'subcategory' => 'revenue',
                'data_type' => 'currency',
                'unit' => 'USD',
                'decimal_places' => 2,
                'aggregation_method' => 'avg',
                'rollup_intervals' => json_encode(['daily', 'weekly', 'monthly']),
                'collection_method' => 'computed',
                'ai_importance' => 'high',
                'is_active' => true,
            ],
            [
                'id' => DB::raw('gen_random_uuid()'),
                'metric_key' => 'financial.ltv',
                'name' => 'Lifetime Value',
                'description' => 'Estimated lifetime value of a customer',
                'category' => 'financial',
                'subcategory' => 'revenue',
                'data_type' => 'currency',
                'unit' => 'USD',
                'decimal_places' => 2,
                'aggregation_method' => 'avg',
                'rollup_intervals' => json_encode(['monthly']),
                'collection_method' => 'computed',
                'ai_importance' => 'high',
                'is_active' => true,
            ],
            [
                'id' => DB::raw('gen_random_uuid()'),
                'metric_key' => 'financial.cac',
                'name' => 'Customer Acquisition Cost',
                'description' => 'Average cost to acquire a new customer',
                'category' => 'financial',
                'subcategory' => 'cost',
                'data_type' => 'currency',
                'unit' => 'USD',
                'decimal_places' => 2,
                'aggregation_method' => 'avg',
                'rollup_intervals' => json_encode(['monthly']),
                'collection_method' => 'computed',
                'ai_importance' => 'high',
                'is_active' => true,
            ],

            // Infrastructure Metrics
            [
                'id' => DB::raw('gen_random_uuid()'),
                'metric_key' => 'infrastructure.server_uptime',
                'name' => 'Server Uptime',
                'description' => 'Percentage of time servers are operational',
                'category' => 'infrastructure',
                'subcategory' => 'availability',
                'data_type' => 'percentage',
                'unit' => '%',
                'decimal_places' => 2,
                'aggregation_method' => 'avg',
                'rollup_intervals' => json_encode(['hourly', 'daily', 'weekly', 'monthly']),
                'warning_threshold' => 99.0,
                'warning_direction' => 'below',
                'critical_threshold' => 95.0,
                'critical_direction' => 'below',
                'collection_method' => 'scheduled',
                'collection_interval_seconds' => 60,
                'ai_importance' => 'critical',
                'is_active' => true,
            ],
            [
                'id' => DB::raw('gen_random_uuid()'),
                'metric_key' => 'infrastructure.response_time',
                'name' => 'API Response Time',
                'description' => 'Average API response time in milliseconds',
                'category' => 'infrastructure',
                'subcategory' => 'performance',
                'data_type' => 'duration',
                'unit' => 'ms',
                'decimal_places' => 0,
                'aggregation_method' => 'avg',
                'rollup_intervals' => json_encode(['hourly', 'daily', 'weekly', 'monthly']),
                'warning_threshold' => 500,
                'warning_direction' => 'above',
                'critical_threshold' => 1000,
                'critical_direction' => 'above',
                'collection_method' => 'realtime',
                'ai_importance' => 'high',
                'is_active' => true,
            ],
            [
                'id' => DB::raw('gen_random_uuid()'),
                'metric_key' => 'infrastructure.error_rate',
                'name' => 'Error Rate',
                'description' => 'Percentage of requests that result in errors',
                'category' => 'infrastructure',
                'subcategory' => 'reliability',
                'data_type' => 'percentage',
                'unit' => '%',
                'decimal_places' => 2,
                'aggregation_method' => 'avg',
                'rollup_intervals' => json_encode(['hourly', 'daily', 'weekly', 'monthly']),
                'warning_threshold' => 1.0,
                'warning_direction' => 'above',
                'critical_threshold' => 5.0,
                'critical_direction' => 'above',
                'collection_method' => 'realtime',
                'ai_importance' => 'critical',
                'is_active' => true,
            ],

            // Email Metrics
            [
                'id' => DB::raw('gen_random_uuid()'),
                'metric_key' => 'email.bounce_rate',
                'name' => 'Email Bounce Rate',
                'description' => 'Percentage of emails that bounced',
                'category' => 'email',
                'subcategory' => 'deliverability',
                'data_type' => 'percentage',
                'unit' => '%',
                'decimal_places' => 2,
                'aggregation_method' => 'avg',
                'rollup_intervals' => json_encode(['hourly', 'daily', 'weekly', 'monthly']),
                'warning_threshold' => 5.0,
                'warning_direction' => 'above',
                'critical_threshold' => 10.0,
                'critical_direction' => 'above',
                'collection_method' => 'event_driven',
                'ai_importance' => 'high',
                'is_active' => true,
            ],
            [
                'id' => DB::raw('gen_random_uuid()'),
                'metric_key' => 'email.complaint_rate',
                'name' => 'Email Complaint Rate',
                'description' => 'Percentage of emails marked as spam',
                'category' => 'email',
                'subcategory' => 'deliverability',
                'data_type' => 'percentage',
                'unit' => '%',
                'decimal_places' => 4,
                'aggregation_method' => 'avg',
                'rollup_intervals' => json_encode(['hourly', 'daily', 'weekly', 'monthly']),
                'warning_threshold' => 0.1,
                'warning_direction' => 'above',
                'critical_threshold' => 0.5,
                'critical_direction' => 'above',
                'collection_method' => 'event_driven',
                'ai_importance' => 'high',
                'is_active' => true,
            ],
            [
                'id' => DB::raw('gen_random_uuid()'),
                'metric_key' => 'email.deliverability',
                'name' => 'Email Deliverability Rate',
                'description' => 'Percentage of emails successfully delivered',
                'category' => 'email',
                'subcategory' => 'deliverability',
                'data_type' => 'percentage',
                'unit' => '%',
                'decimal_places' => 2,
                'aggregation_method' => 'avg',
                'rollup_intervals' => json_encode(['hourly', 'daily', 'weekly', 'monthly']),
                'warning_threshold' => 95.0,
                'warning_direction' => 'below',
                'critical_threshold' => 90.0,
                'critical_direction' => 'below',
                'collection_method' => 'computed',
                'ai_importance' => 'critical',
                'is_active' => true,
            ],

            // Growth Metrics
            [
                'id' => DB::raw('gen_random_uuid()'),
                'metric_key' => 'growth.new_customers',
                'name' => 'New Customers',
                'description' => 'Number of new customers acquired',
                'category' => 'growth',
                'subcategory' => 'acquisition',
                'data_type' => 'count',
                'unit' => 'count',
                'decimal_places' => 0,
                'aggregation_method' => 'sum',
                'rollup_intervals' => json_encode(['daily', 'weekly', 'monthly']),
                'collection_method' => 'event_driven',
                'ai_importance' => 'high',
                'is_active' => true,
            ],
            [
                'id' => DB::raw('gen_random_uuid()'),
                'metric_key' => 'growth.conversion_rate',
                'name' => 'Conversion Rate',
                'description' => 'Percentage of leads that convert to customers',
                'category' => 'growth',
                'subcategory' => 'conversion',
                'data_type' => 'percentage',
                'unit' => '%',
                'decimal_places' => 2,
                'aggregation_method' => 'avg',
                'rollup_intervals' => json_encode(['daily', 'weekly', 'monthly']),
                'collection_method' => 'computed',
                'ai_importance' => 'high',
                'is_active' => true,
            ],

            // System Metrics
            [
                'id' => DB::raw('gen_random_uuid()'),
                'metric_key' => 'system.queue_depth',
                'name' => 'Queue Depth',
                'description' => 'Number of messages waiting in queue',
                'category' => 'system',
                'subcategory' => 'queues',
                'data_type' => 'count',
                'unit' => 'count',
                'decimal_places' => 0,
                'aggregation_method' => 'last',
                'rollup_intervals' => json_encode(['hourly', 'daily', 'weekly', 'monthly']),
                'warning_threshold' => 1000,
                'warning_direction' => 'above',
                'critical_threshold' => 5000,
                'critical_direction' => 'above',
                'collection_method' => 'scheduled',
                'collection_interval_seconds' => 60,
                'ai_importance' => 'high',
                'is_active' => true,
            ],
            [
                'id' => DB::raw('gen_random_uuid()'),
                'metric_key' => 'system.jobs_failed',
                'name' => 'Failed Jobs',
                'description' => 'Number of failed background jobs',
                'category' => 'system',
                'subcategory' => 'jobs',
                'data_type' => 'count',
                'unit' => 'count',
                'decimal_places' => 0,
                'aggregation_method' => 'sum',
                'rollup_intervals' => json_encode(['hourly', 'daily', 'weekly', 'monthly']),
                'warning_threshold' => 10,
                'warning_direction' => 'above',
                'critical_threshold' => 50,
                'critical_direction' => 'above',
                'collection_method' => 'event_driven',
                'ai_importance' => 'high',
                'is_active' => true,
            ],

            // Cost Metrics
            [
                'id' => DB::raw('gen_random_uuid()'),
                'metric_key' => 'cost.aws_total',
                'name' => 'AWS Total Cost',
                'description' => 'Total AWS infrastructure costs',
                'category' => 'cost',
                'subcategory' => 'aws',
                'data_type' => 'currency',
                'unit' => 'USD',
                'decimal_places' => 2,
                'aggregation_method' => 'sum',
                'rollup_intervals' => json_encode(['daily', 'weekly', 'monthly']),
                'collection_method' => 'scheduled',
                'collection_interval_seconds' => 3600,
                'ai_importance' => 'high',
                'is_active' => true,
            ],
            [
                'id' => DB::raw('gen_random_uuid()'),
                'metric_key' => 'cost.email_total',
                'name' => 'Email Infrastructure Cost',
                'description' => 'Total cost of email infrastructure',
                'category' => 'cost',
                'subcategory' => 'email',
                'data_type' => 'currency',
                'unit' => 'USD',
                'decimal_places' => 2,
                'aggregation_method' => 'sum',
                'rollup_intervals' => json_encode(['daily', 'weekly', 'monthly']),
                'collection_method' => 'scheduled',
                'collection_interval_seconds' => 3600,
                'ai_importance' => 'normal',
                'is_active' => true,
            ],
            [
                'id' => DB::raw('gen_random_uuid()'),
                'metric_key' => 'cost.ai_total',
                'name' => 'AI API Cost',
                'description' => 'Total cost of AI API calls',
                'category' => 'cost',
                'subcategory' => 'ai',
                'data_type' => 'currency',
                'unit' => 'USD',
                'decimal_places' => 2,
                'aggregation_method' => 'sum',
                'rollup_intervals' => json_encode(['daily', 'weekly', 'monthly']),
                'collection_method' => 'event_driven',
                'ai_importance' => 'normal',
                'is_active' => true,
            ],
        ];

        foreach ($metrics as $metric) {
            // Check if metric already exists
            $exists = DB::table('ops.metric_definitions')
                ->where('metric_key', $metric['metric_key'])
                ->exists();

            if (!$exists) {
                DB::table('ops.metric_definitions')->insert($metric);
            }
        }

        $this->command->info('Metric definitions seeded successfully.');
    }
}

