<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('knowledge_base', function (Blueprint $table) {
            // UUID will be generated by Laravel/application code
            $table->uuid('id')->primary();
            $table->uuid('tenant_id');
            $table->text('title');
            $table->text('content');
            $table->text('category')->nullable();
            $table->text('subcategory')->nullable();
            $table->json('industry_codes')->nullable();
            
            // Vector status
            $table->string('embedding_status', 20)->default('pending');
            $table->text('embedding')->nullable(); // pgvector type - stored as text in Laravel
            
            // Access control
            $table->boolean('is_public')->default(true);
            $table->json('allowed_agents')->nullable();
            
            // Source & validation
            $table->string('source', 20)->nullable();
            $table->text('source_url')->nullable();
            $table->string('validation_status', 20)->default('unverified');
            $table->timestampTz('validated_at')->nullable();
            $table->uuid('validated_by')->nullable();
            
            // Usage metrics
            $table->integer('usage_count')->default(0);
            $table->integer('helpful_count')->default(0);
            $table->integer('not_helpful_count')->default(0);
            
            // Metadata
            $table->json('tags')->nullable();
            $table->jsonb('metadata')->nullable();
            
            $table->uuid('created_by')->nullable();
            $table->timestampTz('created_at')->default(DB::raw('NOW()'));
            $table->timestampTz('updated_at')->default(DB::raw('NOW()'));
            
            // Indexes
            $table->index('tenant_id');
            $table->index('category');
            $table->index('embedding_status');
            $table->index('validation_status');
            $table->index('source');
        });
        
        // Create indexes in separate transactions to avoid transaction abort
        try {
            // Add vector index separately (pgvector) - only if extension is available
            DB::statement('CREATE INDEX IF NOT EXISTS idx_knowledge_base_embedding ON knowledge_base USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100)');
        } catch (\Exception $e) {
            // Vector extension not available - skip vector index
            Log::warning('Vector index creation skipped: ' . $e->getMessage());
        }
        
        // Full-text search indexes
        try {
            DB::statement("CREATE INDEX IF NOT EXISTS idx_knowledge_base_title_search ON knowledge_base USING GIN(to_tsvector('english', title))");
        } catch (\Exception $e) {
            Log::warning('Title search index creation failed: ' . $e->getMessage());
        }
        
        try {
            DB::statement("CREATE INDEX IF NOT EXISTS idx_knowledge_base_content_search ON knowledge_base USING GIN(to_tsvector('english', content))");
        } catch (\Exception $e) {
            Log::warning('Content search index creation failed: ' . $e->getMessage());
        }
        
        // GIN indexes for JSONB/arrays
        try {
            DB::statement('CREATE INDEX IF NOT EXISTS idx_knowledge_base_tags ON knowledge_base USING GIN(tags)');
        } catch (\Exception $e) {
            Log::warning('Tags index creation failed: ' . $e->getMessage());
        }
        
        try {
            DB::statement('CREATE INDEX IF NOT EXISTS idx_knowledge_base_metadata ON knowledge_base USING GIN(metadata)');
        } catch (\Exception $e) {
            Log::warning('Metadata index creation failed: ' . $e->getMessage());
        }
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('knowledge_base');
    }
};
